[window]
opacity = 0.75
padding.x = 25
padding.y = 25

[colors]
[colors.primary]
background = "#130c0b"
foreground = "#e2a680"

[colors.normal]
black   = "#130c0b"
red     = "#25829b"
green   = "#c52a21"
yellow  = "#db5f0c"
blue    = "#d7790b"
magenta = "#936a4c"
cyan    = "#b07a57"
white   = "#e2a680"

[colors.bright]
black   = "#685050"
red     = "#d7790b"
green   = "#c52a21"
yellow  = "#db5f0c"
blue    = "#d7790b"
magenta = "#936a4c"
cyan    = "#b07a57"
white   = "#e2a680"

[colors.cursor]
text   = "#130c0b"
cursor = "#e2a680"
