# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#130c0b"

# Main text color
theme[main_fg]="#e2a680"

# Title color for boxes
theme[title]="#e2a680"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d7790b"

# Background color of selected item in processes box
theme[selected_bg]="#e2a680"

# Foreground color of selected item in processes box
theme[selected_fg]="#d7790b"

# Color of inactive/disabled text
theme[inactive_fg]="#685050"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#f7be9b"

# Background color of the percentage meters
theme[meter_bg]="#e2a680"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#f7be9b"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#c52a21"
theme[mem_box]="#25829b"
theme[net_box]="#25829b"
theme[proc_box]="#d7790b"

# Box divider line and small boxes line color
theme[div_line]="#685050"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#25829b"
theme[temp_mid]="#db5f0c"
theme[temp_end]="#25829b"

# CPU graph colors (Teal -> Blue -> Purple)
theme[cpu_start]="#b07a57"
theme[cpu_mid]="#d7790b"
theme[cpu_end]="#c52a21"

# Mem/Disk free meter
theme[free_start]="#c52a21"
theme[free_mid]="#d7790b"
theme[free_end]="#b07a57"

# Mem/Disk cached meter
theme[cached_start]="#d7790b"
theme[cached_mid]="#b07a57"
theme[cached_end]="#c52a21"

# Mem/Disk available meter
theme[available_start]="#db5f0c"
theme[available_mid]="#25829b"
theme[available_end]="#25829b"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#25829b"
theme[used_mid]="#b07a57"
theme[used_end]="#d7790b"

# Download graph colors
theme[download_start]="#db5f0c"
theme[download_mid]="#25829b"
theme[download_end]="#25829b"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#25829b"
theme[upload_mid]="#b07a57"
theme[upload_end]="#d7790b"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#b07a57"
theme[process_mid]="#d7790b"
theme[process_end]="#c52a21"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#130c0b"
theme[gradient_color_1]="#1a1a1a"
theme[gradient_color_2]="#e2a680"
theme[gradient_color_3]="#685050"
theme[gradient_color_4]="#b98667"
theme[gradient_color_5]="#e2a680"
theme[gradient_color_6]="#f7be9b"
theme[gradient_color_7]="#f8c6a7"
