# UI Colors (extended)
accent = "#c52a21"
cursor = "#e2a680"

# Primary colors
foreground = "#e2a680"
background = "#130c0b"

# Selection colors
selection_foreground = "#130c0b"
selection_background = "#e2a680"

# Normal colors (ANSI 0-7)
color0 = "#130c0b"
color1 = "#25829b"
color2 = "#c52a21"
color3 = "#db5f0c"
color4 = "#d7790b"
color5 = "#936a4c"
color6 = "#b07a57"
color7 = "#e2a680"

# Bright colors (ANSI 8-15)
color8 = "#685050"
color9 = "#d7790b"
color10 = "#c52a21"
color11 = "#db5f0c"
color12 = "#d7790b"
color13 = "#936a4c"
color14 = "#b07a57"
color15 = "#e2a680"
