# Background and foreground colors
background = #000000
foreground = #e2a680
background-opacity = 0.75
window-padding-x = 25
window-padding-y = 25

# Standard colors
palette = 0=#000000
palette = 1=#25829b
palette = 2=#c52a21
palette = 3=#db5f0c
palette = 4=#d7790b
palette = 5=#936a4c
palette = 6=#b07a57
palette = 7=#e2a680

# Bright colors
palette = 8=#685050
palette = 9=#d7790b
palette = 10=#c52a21
palette = 11=#db5f0c
palette = 12=#d7790b
palette = 13=#936a4c
palette = 14=#b07a57
palette = 15=#e2a680
