# Background and foreground colors
background = #000000
foreground = #f6b389
background-opacity = 0.7
window-padding-x = 25
window-padding-y = 25

# Standard colors
palette = 0=#000000
palette = 1=#418fd7
palette = 2=#c52a21
palette = 3=#db5f0c
palette = 4=#ec850c
palette = 5=#9c7151
palette = 6=#bb825d
palette = 7=#f6b389

# Bright colors
palette = 8=#433c3c
palette = 9=#ec850c
palette = 10=#c52a21
palette = 11=#db5f0c
palette = 12=#ec850c
palette = 13=#9c7151
palette = 14=#bb825d
palette = 15=#f6b389
