$activeBorderColor = rgb(ec850c)

general {
    layout = dwindle
    gaps_in = 10
    gaps_out = 20	
    border_size = 3
    col.active_border = $activeBorderColor
    col.inactive_border = rgba(241002FF)
}

group {
    col.border_active = $activeBorderColor
}

decoration {
    rounding = 16
	  dim_special = 0.0
    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
        enabled = true
        size = 4
        passes = 3
        new_optimizations = true
        xray = false
		    contrast = 0.85
		    brightness = 0.5
		    noise = 0.15
		    vibrancy = 1.0
		    vibrancy_darkness = 0.1
		    special = true
        # ignore_opacity = true
        # popups_ignorealpha = 0.5
        # input_methods_ignorealpha = 0.5
    }
}

animations {
    enabled = yes
    bezier = wind, 0.02, 0.9, 0.1, 1.03
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 6, wind, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = fade, 1, 10, default
    animation = workspaces, 1, 1, wind
}
