background            #000000
foreground            #e2a680

background_opacity 0.85
window_padding_width 25
window_padding_height 25

# black
color0  #000000
color8  #685050

# red
color1  #25829b
color9  #d7790b

# green
color2  #c52a21
color10 #c52a21

# yellow
color3  #db5f0c
color11 #db5f0c

# blue
color4  #d7790b
color12 #d7790b

# magenta
color5  #936a4c
color13 #936a4c

#cyan
color6  #b07a57
color14 #b07a57

#white
color7  #e2a680
color15 #e2a680


